### ISSUE TITLE
Support for merging keys from custom types

### ISSUE THREAD

**Issue by alunbestor** [th-in-gs/YACYAML#10]
At the moment YACYAML will silently fail when merging keys from maps that have been given a custom type. As a contrived example, take this construction:

``` yaml
- !GameEnemy &basic-guard
    name: Basic Guard
    color: blue
    hitPoints: 15
    attackRange: 5

- !GameEnemy
   <<: *basic-guard
   name: Royal Guard
   color: red
   # This enemy will have no hitPoints or attackRange

```

This is because [YACYAML's merge-key handling](https://github.com/th-in-gs/YACYAML/blob/master/YACYAML/Unarchiving/YACYAMLUnarchivingExtensions.m#L620) only supports `NSDictionaries` (and `NSArrays` of `NSDictionaries`) and silently fails with other types. In the example above: by the time the unarchive process gets reaches Royal Guard's merge key, Basic Guard is already an instance of `GameEnemy` and not an `NSDictionary`, and the merge will fail.

In the above example, the workaround would be to separate the shared properties off to a regular map and then merge that map into both Basic Guard and Royal Guard; but this complicates the structure of the YAML document solely for the sake of the parser and makes it harder to follow.

(It's unclear from the [YAML merge key spec](http://yaml.org/type/merge.html) whether merging from custom map types was ever intended; but it is supported by some other YAML implementations and is useful for the sort of taxonomy demonstrated in the example.)

<hr>

One possible way to implement this:

[When parsing a map with a custom type](https://github.com/th-in-gs/YACYAML/blob/master/YACYAML/Unarchiving/YACYAMLUnarchivingObject.m#L215), annotate the resulting object (using `objc_setAssociatedObject`) with the `NSDictionary` for the original map. Then, check for such an annotation later when handling merge-keys.

(The unarchiver would need to be conscientious about cleaning up the annotations once the whole unarchiving process is complete. I'm unclear about where the best place to do this would be, since `YACYAMLKeyedUnarchiver` does not have an explicit `-finishDecoding` method, like `NSKeyedUnarchiver` has for this kind of cleanup.)
